

const RecipeData = [
  {
    url: require('./img/1-1.jpeg'),
    name: 'Perfect Roasted Garlic',
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-2.jpeg'),
    name: "'No' Salt",
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'square',
    notes: 'need to crop image'
  },
  {
    url: require('./img/1-2.jpeg'),
    name: 'Homeade Chili Powder',
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'horizontal',
    notes: 'need to crop image'
  },
  {
    url: require('./img/1-3.jpeg'),
    name: 'Pennsylvania Quiche',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/1-3.jpeg'),
    name: 'Pennsylvania Pickled Beets & Eggs',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    category3: 'PICKLING',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-4.jpeg'),
    name: 'Kentucky Mint Julep (Story)',
    category1: "DRINKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-5.jpeg'),
    name: 'Kentucky Mint Julep',
    category1: "DRINKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-5.jpeg'),
    name: 'Spicy Bloody Mary',
    category1: "DRINKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/2.jpeg'),
    name: 'Lemon Zucchini Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/2.jpeg'),
    name: 'Old-Fashioned Blueberry Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/3.jpeg'),
    name: 'High-Top Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
    notes: 'add lemony blueberry variation'
  },
  {
    url: require('./img/3.jpeg'),
    name: 'Cheese-Stuffed Pecan Pumpkin Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/3.jpeg'),
    name: 'Crunchy Lemon-Nut Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/4.jpeg'),
    name: 'Black Cherry Almond Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/4.jpeg'),
    name: 'Bacon & Corn Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/5.jpeg'),
    name: 'Stuffed French Toast from The Hershey Pantry',
    category1: "BREAKFAST",
    category2: '',
    orientation: 'vertical',
    notes: 'recipe from the 60s'
  },
  {
    url: require('./img/5.jpeg'),
    name: 'Stuffed French Toast from Walt Disney World Polynesian Village Resort',
    category1: "BREAKFAST",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/6.jpeg'),
    name: 'Crab Meat Benedict',
    category1: "BREAKFAST",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/6.jpeg'),
    name: 'Crab Imperial',
    category1: "SIDES",
    category2: "SEAFOOD",
    category3: "SMALL PLATES & SNACKS",
    orientation: 'vertical',
  },
  {
    url: require('./img/7.jpeg'),
    name: 'Sesame-Topped Water Crackers',
    category1: "BREADS & CRACKERS",
    category2: "SMALL PLATES & SNACKS",
    orientation: 'horizontal',
  },
  {
    url: require('./img/8.jpeg'),
    name: 'Cheese Loaf',
    category1: "SIDES",
    category2: "BREADS & CRACKERS",
    orientation: 'horizontal',
  },
  {
    url: require('./img/9.jpeg'),
    name: 'Peanut Butter Bread',
    category1: "BREADS & CRACKERS",
    category2: "DESSERTS",
    orientation: 'vertical',
  },
  {
    url: require('./img/9.jpeg'),
    name: 'Curried Puffs with Parmesean & Chives',
    category1: "SMALL PLATES & SNACKS",
    category2: "BREADS & CRACKERS",
    orientation: 'vertical',
  },
  {
    url: require('./img/9.jpeg'),
    name: 'Fiesta Bread',
    category1: "BREADS & CRACKERS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/10.jpeg'),
    name: 'Honey Graham Crackers',
    category1: "BREADS & CRACKERS",
    category2: "SMALL PLATES & SNACKS",
    orientation: 'vertical',
  },
  {
    url: require('./img/11.jpeg'),
    name: 'Avocado Spread',
    category1: "SPREADS & DIPS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/12,20.jpeg'),
    name: 'Impossible Quiche Tarts',
    category1: "SMALL PLATES & SNACKS",
    category2: "BREAKFAST",
    orientation: 'vertical',
  },
  {
    url: require('./img/12,20.jpeg'),
    name: 'Pineapple Cheese Spread',
    category1: "SPREADS & DIPS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/13-1,24.jpeg'),
    name: 'Hot & Spicy Nuts',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/13-1,24.jpeg'),
    name: 'Lox & Cream Cheese Spread',
    category1: "SPREADS & DIPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/13-2.jpeg'),
    name: 'Hickory Quick BBQ Sauce',
    category1: "SAUCES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/13-2.jpeg'),
    name: 'Garlic Salsa',
    category1: "SPREADS & DIPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/13-2.jpeg'),
    name: 'Jamaican Barbecue Sauce',
    category1: "SAUCES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/14.jpeg'),
    name: 'Stuffed Mushrooms',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/14.jpeg'),
    name: 'Mushroom Marinade',
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/15,18.jpeg'),
    name: 'Olive Balls',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/15,18.jpeg'),
    name: 'Asparagus Spear Sandwiches',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    category3: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/16.jpeg'),
    name: 'Herb Butter Zucchini Fans',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/17.jpeg'),
    name: 'Zucchini Squares',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/19.jpeg'),
    name: 'Tomato Rarebits',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/21.jpeg'),
    name: 'Seafood Quiche Squares',
    category1: "SMALL PLATES & SNACKS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/24,53.jpeg'),
    name: "James Beard's Coleslaw",
    category1: "SIDES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/24,53.jpeg'),
    name: "Tomato Spinach Salad",
    category1: "SALADS & DRESSINGS",
    category2: "",
    orientation: 'vertical',
  },
  {
    url: require('./img/25.jpeg'),
    name: 'Lettuce with Hot Bacon Dressing',
    category1: "SALADS & DRESSINGS",
    category2: "",
    orientation: 'vertical',
  },
  {
    url: require('./img/26.jpeg'),
    name: 'Caesar Salad',
    category1: "SALADS & DRESSINGS",
    category2: "",
    orientation: 'horizontal',
  },
  {
    url: require('./img/27.jpeg'),
    name: 'Basil Walnut Vinaigrette',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/28.jpeg'),
    name: 'Herbed Vinegars',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/28.jpeg'),
    name: 'Our Favorite Vinaigrette',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'square',
  },
  {
    url: require('./img/29.jpeg'),
    name: 'Parmesean Salad Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/30.jpeg'),
    name: "Connie's Poppy Seed Dressing",
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'square',
  },
  {
    url: require('./img/31.jpeg'),
    name: 'Avocado Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/31.jpeg'),
    name: 'Creamy Italian Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/31.jpeg'),
    name: 'Blue Cheese Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/32.jpeg'),
    name: 'Crab Soup',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/33.jpeg'),
    name: 'Onion Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/34.jpeg'),
    name: 'Crab Bisque',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/35.jpeg'),
    name: 'Spicy Crab Soup',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'horizontal',
  },
  {
    url: require('./img/36.jpeg'),
    name: 'Scallop Bisque',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/37.jpeg'),
    name: 'Conch Chowder',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/37.jpeg'),
    name: 'Conch Chowder II',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/38.jpeg'),
    name: 'Cream of Cauliflower Soup',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/39.jpeg'),
    name: 'Hot Cream of Spinach Soup',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/40.jpeg'),
    name: 'Cream of Spinach Soup with Prosciutto & Peppered Croutons',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/41.jpeg'),
    name: 'Spinach Garlic Soup',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/42.jpeg'),
    name: 'Brie Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/43.jpeg'),
    name: 'Cheese Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/44.jpeg'),
    name: 'Best Ever Beer Cheese Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/45.jpeg'),
    name: 'Creamy Potato Soup with Roasted Garlic',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/46.jpeg'),
    name: 'Potato & Garlic Soup with Rosemary Butter',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/47.jpeg'),
    name: 'Very Creamy Potato Cheese Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/48.jpeg'),
    name: 'Vegetarian Chili (Ingredients)',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/49.jpeg'),
    name: 'Vegetarian Chili (Recipe)',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/50.jpeg'),
    name: 'Tangy Barbecued Beef Sandwiches',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/51.jpeg'),
    name: 'Brie Souffle',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    orientation: 'vertical',
  },
  {
    url: require('./img/52.jpeg'),
    name: 'Broccoli Cheese Souffle',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    orientation: 'vertical',
  },
  {
    url: require('./img/53.jpeg'),
    name: 'Sherried Mushrooms',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    category3: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/54.jpeg'),
    name: 'Herbed Asparagus Saute',
    category1: "SIDES",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/55.jpeg'),
    name: 'Tangy Mustard Cauliflower',
    category1: "SIDES",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/57.jpeg'),
    name: 'Baked Mixed Vegetable Salad',
    category1: "SALADS & DRESSINGS",
    category2: "",
    category3: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/58.jpeg'),
    name: 'Spinach Stuffed Artichoke Bottoms',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/59.jpeg'),
    name: "Myrt's Baked Beans",
    category1: "SIDES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/59.jpeg'),
    name: "Barb's Baked Beans",
    category1: "SIDES",
    category2: '',
    orientation: 'square',
  },
  {
    url: require('./img/60.jpeg'),
    name: 'Veggie Cakes',
    category1: "SIDES",
    category2: "VEGGIE",
    category3: "SMALL PLATES & SNACKS",
    orientation: 'vertical',
  },
  {
    url: require('./img/61.jpeg'),
    name: 'Jalepeno Corn Pudding',
    category1: "",
    category2: "SIDES",
    orientation: 'square',
  },
  {
    url: require('./img/62.jpeg'),
    name: 'Easy Corn Fritters',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    category3: "BREADS & CRACKERS",
    orientation: 'vertical',
  },
  {
    url: require('./img/63.jpeg'),
    name: 'Chicken Tchoupitoulas',
    category1: "ENTREES",
    category2: "CHICKEN",
    orientation: 'vertical',
  },
  {
    url: require('./img/64.jpeg'),
    name: 'Chicken, Andouille Smoked Sausage and Tasso Jambalaya with Creole Sauce',
    category1: "ENTREES",
    category2: "CHICKEN",
    category3: "PORK",
    orientation: 'vertical',
  },
  {
    url: require('./img/65.jpeg'),
    name: 'Cajun Pot Roast',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/66.jpeg'),
    name: 'Cabbage Rolls',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/67.jpeg'),
    name: 'Beef Stroganoff',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/67.jpeg'),
    name: 'Beef Wellington',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/68.jpeg'),
    name: 'Chiles Rellenos Casserole',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/68.jpeg'),
    name: 'South-of-the-Border Lasagna',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/69.jpeg'),
    name: 'Cola Roast',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal vertical',
  },
  {
    url: require('./img/70.jpeg'),
    name: 'Sugar-Smoked Chicken',
    category1: "ENTREES",
    category2: "CHICKEN",
    orientation: 'vertical',
  },
  {
    url: require('./img/71.jpeg'),
    name: 'Chicken Arlette',
    category1: "ENTREES",
    category2: "CHICKEN",
    orientation: 'horizontal',
  },
  {
    url: require('./img/72.jpeg'),
    name: 'Baked Broccoli Gnocchi',
    category1: "ENTREES",
    category2: 'VEGGIE',
    orientation: 'vertical',
  },
  {
    url: require('./img/73.jpeg'),
    name: 'Eggplant Crepes filled with Ricotta Cheese',
    category1: "ENTREES",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/74.jpeg'),
    name: 'Shrimp Benihana',
    category1: "ENTREES",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/75.jpeg'),
    name: 'Sweet & Sour Meatballs',
    category1: "ENTREES",
    category2: "PORK",
    orientation: 'vertical',
  },
  {
    url: require('./img/76.jpeg'),
    name: 'Egg Foo Yong',
    category1: "ENTREES",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/77.jpeg'),
    name: 'Spicy Szechuan Noodles',
    category1: "ENTREES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/78.jpeg'),
    name: 'Hunam Beef',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/79.jpeg'),
    name: 'Beef Roulades Braised in Beer',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/80.jpeg'),
    name: 'Steak Au Poivre (Pepper Steak)',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/82.jpeg'),
    name: 'Veal & Crabmeat Medici',
    category1: "ENTREES",
    category2: "SEAFOOD",
    category3: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/83.jpeg'),
    name: "Joe's Florida Stone Crab Mustard Sauce",
    category1: "SPREADS & DIPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/85.jpeg'),
    name: 'Sauce Bearnaise',
    category1: "SAUCES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/86.jpeg'),
    name: 'Blender Hollandaise',
    category1: "SAUCES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/87.jpeg'),
    name: 'Sherried Cream Sauce',
    category1: "SAUCES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/88.jpeg'),
    name: 'Lemon Meringue Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal vertical',
  },
  {
    url: require('./img/89.jpeg'),
    name: 'Key Lime Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal vertical',
  },
  {
    url: require('./img/90.jpeg'),
    name: 'Perfect Lemon Meringue Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
  {
    url: require('./img/90.jpeg'),
    name: 'Magic Lemon Meringue Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/91.jpeg'),
    name: 'The Ultimate Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/92.jpeg'),
    name: 'Apple Cheddar Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/93.jpeg'),
    name: 'Praline Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/94.jpeg'),
    name: 'Pumpkin Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/95.jpeg'),
    name: 'Hotel Hershey Chocolate Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/96.jpeg'),
    name: 'Cafe au Lait Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/97.jpeg'),
    name: 'Apple Almond Linzer Torte',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/97.jpeg'),
    name: 'Carameled Apple Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/98,104.jpeg'),
    name: 'Microwave Spiced Nuts',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/98,104.jpeg'),
    name: 'Peanut Butter Football Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/98,104.jpeg'),
    name: 'Three Ginger Gingerbread Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/99.jpeg'),
    name: 'Caramel Apple Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/99.jpeg'),
    name: 'Coffee Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/100.jpeg'),
    name: 'Nutmeg Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/101.jpeg'),
    name: 'Black Ginger Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/102-1.jpeg'),
    name: 'Spicy Pumpkin Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/102-2.jpeg'),
    name: 'Banana Pie with Hot Buttered Rum Sauce',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
  {
    url: require('./img/102-2.jpeg'),
    name: 'Crumb Top Deep Dish Apple Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/103.jpeg'),
    name: 'Peanut Butter Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/105.jpeg'),
    name: 'Frozen Peanut Butter Pie with Caramel Sauce',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
  {
    url: require('./img/106.jpeg'),
    name: 'Easter Eggs',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/107.jpeg'),
    name: 'Mississippi Mud Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/108.jpeg'),
    name: 'Kahlua Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/109.jpeg'),
    name: 'Chocolate Meringue Kisses',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/110.jpeg'),
    name: 'Butterscotch Krimpets',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/111.jpeg'),
    name: 'Almost Better Than Sex Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/112.jpeg'),
    name: "Hershey's Old Fashioned Chocolate Cake",
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/112.jpeg'),
    name: 'Chocolate Chip Cookies',
    category1: "DESSERTS",
    category2: 'Cookies',
    orientation: 'vertical',
  },
  {
    url: require('./img/114.jpeg'),
    name: 'Best Ever Pie Crust',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
];

module.exports.RecipeData = RecipeData;


