

const RecipeData = [
  {
    url: require('./img/1-1.JPG'),
    name: 'Perfect Roasted Garlic',
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-2.JPG'),
    name: "'No' Salt",
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'square',
    notes: 'need to crop image'
  },
  {
    url: require('./img/1-3.JPG'),
    name: 'Homeade Chili Powder',
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'horizontal',
    notes: 'need to crop image'
  },
  {
    url: require('./img/999.JPG'),
    name: 'Pennsylvania Quiche',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/998.JPG'),
    name: 'Pennsylvania Pickled Beets & Eggs',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    category3: 'PICKLING',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-4.JPG'),
    name: 'Kentucky Mint Julep (Story)',
    category1: "DRINKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-5.JPG'),
    name: 'Kentucky Mint Julep',
    category1: "DRINKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/1-5-2.JPG'),
    name: 'Spicy Bloody Mary',
    category1: "DRINKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/2.JPG'),
    name: 'Lemon Zucchini Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/2-2.JPG'),
    name: 'Old-Fashioned Blueberry Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/3-2.JPG'),
    name: 'High-Top Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
    notes: 'add lemony blueberry variation'
  },
  {
    url: require('./img/3-3.JPG'),
    name: 'Cheese-Stuffed Pecan Pumpkin Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/3-4.JPG'),
    name: 'Crunchy Lemon-Nut Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/4.JPG'),
    name: 'Black Cherry Almond Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/4-2.JPG'),
    name: 'Bacon & Corn Muffins',
    category1: "BREAKFAST",
    category2: "MUFFINS",
    orientation: 'vertical',
  },
  {
    url: require('./img/5.JPG'),
    name: 'Stuffed French Toast from The Hershey Pantry',
    category1: "BREAKFAST",
    category2: '',
    orientation: 'vertical',
    notes: 'recipe from the 60s'
  },
  {
    url: require('./img/5-2.JPG'),
    name: 'Stuffed French Toast from Walt Disney World Polynesian Village Resort',
    category1: "BREAKFAST",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/6.JPG'),
    name: 'Crab Meat Benedict',
    category1: "BREAKFAST",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/6-2.JPG'),
    name: 'Crab Imperial',
    category1: "SIDES",
    category2: "SEAFOOD",
    category3: "SMALL PLATES & SNACKS",
    orientation: 'vertical',
  },
  {
    url: require('./img/7-3.JPG'),
    name: 'Sesame-Topped Water Crackers',
    category1: "BREADS & CRACKERS",
    category2: "SMALL PLATES & SNACKS",
    orientation: 'horizontal',
  },
  {
    url: require('./img/8.JPG'),
    name: 'Cheese Loaf',
    category1: "SIDES",
    category2: "BREADS & CRACKERS",
    orientation: 'horizontal',
  },
  {
    url: require('./img/9-3.JPG'),
    name: 'Peanut Butter Bread',
    category1: "BREADS & CRACKERS",
    category2: "DESSERTS",
    orientation: 'vertical',
  },
  {
    url: require('./img/9-2.JPG'),
    name: 'Fiesta Bread',
    category1: "BREADS & CRACKERS",
    category2: "",
    orientation: 'vertical',
  },
  {
    url: require('./img/9.JPG'),
    name: 'Curried Puffs with Parmesean & Chives',
    category1: "SMALL PLATES & SNACKS",
    category2: "BREADS & CRACKERS",
    orientation: 'vertical',
  },
  {
    url: require('./img/10.JPG'),
    name: 'Honey Graham Crackers',
    category1: "BREADS & CRACKERS",
    category2: "SMALL PLATES & SNACKS",
    orientation: 'vertical',
  },
  {
    url: require('./img/11.JPG'),
    name: 'Avocado Spread',
    category1: "SPREADS & DIPS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/12,20.JPG'),
    name: 'Impossible Quiche Tarts',
    category1: "SMALL PLATES & SNACKS",
    category2: "BREAKFAST",
    orientation: 'vertical',
  },
  {
    url: require('./img/12,20-2.JPG'),
    name: 'Pineapple Cheese Spread',
    category1: "SPREADS & DIPS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/13-1,24.JPG'),
    name: 'Hot & Spicy Nuts',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/13-1,24-2.JPG'),
    name: 'Lox & Cream Cheese Spread',
    category1: "SPREADS & DIPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/84.JPG'),
    name: 'Hickory Quick BBQ Sauce',
    category1: "SAUCES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/84-2.JPG'),
    name: 'Garlic Salsa',
    category1: "SPREADS & DIPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/84-3.JPG'),
    name: 'Jamaican Barbecue Sauce',
    category1: "SAUCES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/14.JPG'),
    name: 'Stuffed Mushrooms',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/14-2.JPG'),
    name: 'Mushroom Marinade',
    category1: "SEASONINGS & MARINADES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/15,18.JPG'),
    name: 'Olive Balls',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/15,18-2.JPG'),
    name: 'Asparagus Spear Sandwiches',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    category3: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/16.JPG'),
    name: 'Herb Butter Zucchini Fans',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/17.JPG'),
    name: 'Zucchini Squares',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/19.JPG'),
    name: 'Tomato Rarebits',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/19-2.JPG'),
    name: 'Tomatoes Filled with Corn Pudding',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/21.JPG'),
    name: 'Seafood Quiche Squares',
    category1: "SMALL PLATES & SNACKS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/24,53.JPG'),
    name: "James Beard's Coleslaw",
    category1: "SIDES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/24,53-2.JPG'),
    name: "Tomato Spinach Salad",
    category1: "SALADS & DRESSINGS",
    category2: "",
    orientation: 'vertical',
  },
  {
    url: require('./img/25.JPG'),
    name: 'Lettuce with Hot Bacon Dressing',
    category1: "SALADS & DRESSINGS",
    category2: "",
    orientation: 'vertical',
  },
  {
    url: require('./img/26.JPG'),
    name: 'Caesar Salad',
    category1: "SALADS & DRESSINGS",
    category2: "",
    orientation: 'horizontal',
  },
  {
    url: require('./img/27.JPG'),
    name: 'Basil Walnut Vinaigrette',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/27-2.JPG'),
    name: 'Herbed Vinegars',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/28.JPG'),
    name: 'Our Favorite Vinaigrette',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'square',
  },
  {
    url: require('./img/29.JPG'),
    name: 'Parmesean Salad Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/30-2.JPG'),
    name: "Connie's Poppy Seed Dressing",
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'square',
  },
  {
    url: require('./img/30.JPG'),
    name: 'Chili Pasta Salad',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/31.JPG'),
    name: 'Avocado Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/31-3.JPG'),
    name: 'Creamy Italian Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/31-4.JPG'),
    name: 'Blue Cheese Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/31-2.JPG'),
    name: 'Buttermilk Salad Dressing',
    category1: "SALADS & DRESSINGS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/32.JPG'),
    name: 'Crab Soup',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/33.JPG'),
    name: 'Onion Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/34.JPG'),
    name: 'Crab Bisque',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/35.JPG'),
    name: 'Spicy Crab Soup',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'horizontal',
  },
  {
    url: require('./img/36.JPG'),
    name: 'Scallop Bisque',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/37.JPG'),
    name: 'Conch Chowder',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/37-2.JPG'),
    name: 'Conch Chowder II',
    category1: "SOUPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/38.JPG'),
    name: 'Cream of Cauliflower Soup',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/39.JPG'),
    name: 'Hot Cream of Spinach Soup',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/40.JPG'),
    name: 'Cream of Spinach Soup with Prosciutto & Peppered Croutons',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/41.JPG'),
    name: 'Spinach Garlic Soup',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/42.JPG'),
    name: 'Brie Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/43.JPG'),
    name: 'Cheese Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/44.JPG'),
    name: 'Best Ever Beer Cheese Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/45.JPG'),
    name: 'Creamy Potato Soup with Roasted Garlic',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/45-2.JPG'),
    name: 'Garlic Soup',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/46.JPG'),
    name: 'Potato & Garlic Soup with Rosemary Butter',
    category1: "SOUPS",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/47.JPG'),
    name: 'Very Creamy Potato Cheese Soup',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/48.JPG'),
    name: 'Vegetarian Chili (Ingredients)',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/49.JPG'),
    name: 'Vegetarian Chili (Recipe)',
    category1: "SOUPS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/50.JPG'),
    name: 'Tangy Barbecued Beef Sandwiches',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/51.JPG'),
    name: 'Brie Souffle',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    orientation: 'vertical',
  },
  {
    url: require('./img/52.JPG'),
    name: 'Broccoli Cheese Souffle',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    orientation: 'vertical',
  },
  {
    url: require('./img/53.JPG'),
    name: 'Sherried Mushrooms',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    category3: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/54.JPG'),
    name: 'Herbed Asparagus Saute',
    category1: "SIDES",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/55.JPG'),
    name: 'Tangy Mustard Cauliflower',
    category1: "SIDES",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/57.JPG'),
    name: 'Baked Mixed Vegetable Salad',
    category1: "SALADS & DRESSINGS",
    category2: "",
    category3: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/58.JPG'),
    name: 'Spinach Stuffed Artichoke Bottoms',
    category1: "SMALL PLATES & SNACKS",
    category2: "VEGGIE",
    orientation: 'horizontal',
  },
  {
    url: require('./img/59.JPG'),
    name: "Myrt's Baked Beans",
    category1: "SIDES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/59-2.JPG'),
    name: "Barb's Baked Beans",
    category1: "SIDES",
    category2: '',
    orientation: 'square',
  },
  {
    url: require('./img/60.JPG'),
    name: 'Veggie Cakes',
    category1: "SIDES",
    category2: "VEGGIE",
    category3: "SMALL PLATES & SNACKS",
    orientation: 'vertical',
  },
  {
    url: require('./img/61.JPG'),
    name: 'Jalepeno Corn Pudding',
    category1: "",
    category2: "SIDES",
    orientation: 'square',
  },
  {
    url: require('./img/62.JPG'),
    name: 'Easy Corn Fritters',
    category1: "SMALL PLATES & SNACKS",
    category2: "SIDES",
    category3: "BREADS & CRACKERS",
    orientation: 'vertical',
  },
  {
    url: require('./img/63.JPG'),
    name: 'Chicken Tchoupitoulas with Bearnaise Sauce',
    category1: "ENTREES",
    category2: "CHICKEN",
    orientation: 'vertical',
  },
  {
    url: require('./img/64.JPG'),
    name: 'Chicken, Andouille Smoked Sausage and Tasso Jambalaya with Creole Sauce',
    category1: "ENTREES",
    category2: "CHICKEN",
    category3: "PORK",
    orientation: 'vertical',
  },
  {
    url: require('./img/65.JPG'),
    name: 'Cajun Pot Roast',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/66.JPG'),
    name: 'Cabbage Rolls',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/67.JPG'),
    name: 'Beef Stroganoff',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/67-2.JPG'),
    name: 'Beef Wellington',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/68.JPG'),
    name: 'Chiles Rellenos Casserole',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/68-2.JPG'),
    name: 'South-of-the-Border Lasagna',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/69.JPG'),
    name: 'Cola Roast',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal vertical',
  },
  {
    url: require('./img/70.JPG'),
    name: 'Sugar-Smoked Chicken',
    category1: "ENTREES",
    category2: "CHICKEN",
    orientation: 'vertical',
  },
  {
    url: require('./img/71.JPG'),
    name: 'Chicken Arlette',
    category1: "ENTREES",
    category2: "CHICKEN",
    orientation: 'horizontal',
  },
  {
    url: require('./img/72.JPG'),
    name: 'Baked Broccoli Gnocchi',
    category1: "ENTREES",
    category2: 'VEGGIE',
    orientation: 'vertical',
  },
  {
    url: require('./img/73.JPG'),
    name: 'Eggplant Crepes filled with Ricotta Cheese',
    category1: "ENTREES",
    category2: "VEGGIE",
    orientation: 'vertical',
  },
  {
    url: require('./img/74.JPG'),
    name: 'Shrimp Benihana',
    category1: "ENTREES",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/75.JPG'),
    name: 'Sweet & Sour Meatballs',
    category1: "ENTREES",
    category2: "PORK",
    orientation: 'vertical',
  },
  {
    url: require('./img/76.JPG'),
    name: 'Egg Foo Yong',
    category1: "ENTREES",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/77.JPG'),
    name: 'Spicy Szechuan Noodles',
    category1: "ENTREES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/78.JPG'),
    name: 'Hunam Beef',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/79.JPG'),
    name: 'Beef Roulades Braised in Beer',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/80.JPG'),
    name: 'Steak Au Poivre (Pepper Steak)',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'horizontal',
  },
  {
    url: require('./img/80-2.JPG'),
    name: 'Steak Au Poivre from Strawberry Hill',
    category1: "ENTREES",
    category2: "BEEF",
    orientation: 'square',
  },
  {
    url: require('./img/82.JPG'),
    name: 'Veal & Crabmeat Medici',
    category1: "ENTREES",
    category2: "SEAFOOD",
    category3: "BEEF",
    orientation: 'vertical',
  },
  {
    url: require('./img/83.JPG'),
    name: "Joe's Florida Stone Crab Mustard Sauce",
    category1: "SPREADS & DIPS",
    category2: "SEAFOOD",
    orientation: 'vertical',
  },
  {
    url: require('./img/85.JPG'),
    name: 'Sauce Bearnaise',
    category1: "SAUCES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/86.JPG'),
    name: 'Blender Hollandaise',
    category1: "SAUCES",
    category2: '',
    orientation: 'horizontal',
  },
  {
    url: require('./img/87.JPG'),
    name: 'Sherried Cream Sauce',
    category1: "SAUCES",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/88.JPG'),
    name: 'Lemon Meringue Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal vertical',
  },
  {
    url: require('./img/89.JPG'),
    name: 'Key Lime Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal vertical',
  },
  {
    url: require('./img/90.JPG'),
    name: 'Perfect Lemon Meringue Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
  {
    url: require('./img/90-2.JPG'),
    name: 'Magic Lemon Meringue Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/91.JPG'),
    name: 'The Ultimate Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/92.JPG'),
    name: 'Apple Cheddar Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/93.JPG'),
    name: 'Praline Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/94.JPG'),
    name: 'Pumpkin Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/95.JPG'),
    name: 'Hotel Hershey Chocolate Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/95.JPG'),
    name: 'Chocolate Cheesecake with Apricot Glaze',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/96-2.JPG'),
    name: 'Cafe au Lait Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/97.JPG'),
    name: 'Apple Almond Linzer Torte',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/97-2.JPG'),
    name: 'Carameled Apple Cheesecake',
    category1: "DESSERTS",
    category2: 'Cheesecake',
    orientation: 'vertical',
  },
  {
    url: require('./img/98,104.JPG'),
    name: 'Microwave Spiced Nuts',
    category1: "SMALL PLATES & SNACKS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/98,104-3.JPG'),
    name: 'Peanut Butter Football Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/98,104-2.JPG'),
    name: 'Three Ginger Gingerbread Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/99.JPG'),
    name: 'Caramel Apple Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/99-2.JPG'),
    name: 'Coffee Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/100.JPG'),
    name: 'Nutmeg Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/101.JPG'),
    name: 'Black Ginger Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/102-1.JPG'),
    name: 'Spicy Pumpkin Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/102-2.JPG'),
    name: 'Banana Pie with Hot Buttered Rum Sauce',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
  {
    url: require('./img/102-2-2.JPG'),
    name: 'Crumb Top Deep Dish Apple Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/102-1-2.JPG'),
    name: 'Praline Pumpkin Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/103.JPG'),
    name: 'Peanut Butter Pie',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'horizontal',
  },
  {
    url: require('./img/105.JPG'),
    name: 'Frozen Peanut Butter Pie with Caramel Sauce',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
  {
    url: require('./img/106.JPG'),
    name: 'Easter Eggs',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/107.JPG'),
    name: 'Mississippi Mud Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/108.JPG'),
    name: 'Fuzzy Navel Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/108-2.JPG'),
    name: 'Kahlua Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/109.JPG'),
    name: 'Chocolate Meringue Kisses',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/110.JPG'),
    name: 'Butterscotch Krimpets',
    category1: "DESSERTS",
    category2: '',
    orientation: 'vertical',
  },
  {
    url: require('./img/111.JPG'),
    name: 'Almost Better Than Sex Cake',
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'horizontal',
  },
  {
    url: require('./img/112.JPG'),
    name: "Hershey's Old Fashioned Chocolate Cake",
    category1: "DESSERTS",
    category2: 'Cake',
    orientation: 'vertical',
  },
  {
    url: require('./img/113.JPG'),
    name: 'Chocolate Chip Cookies',
    category1: "DESSERTS",
    category2: 'Cookies',
    orientation: 'vertical',
  },
  {
    url: require('./img/114.JPG'),
    name: 'Best Ever Pie Crust',
    category1: "DESSERTS",
    category2: 'Pie',
    orientation: 'vertical',
  },
];

module.exports.RecipeData = RecipeData;


